language: java
jdk:
    - openjdk8
script:
    - mvn verify -B
after_script:
    - env
    - "[[ $TRAVIS_PULL_REQUEST == false ]] && mvn sonar:sonar -Dsonar.organization=slfotg-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}"
