language: java
jdk:
    - oraclejdk8
script:
    - mvn verify -B
after_script:
    - env
    - "[[ $TRAVIS_PULL_REQUEST == false ]] && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.organization=slfotg-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}"
